sudo: false
dist: trusty
language: c

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
cache: ccache

script:
  - ccache -M 0
  - make -j3 CC="ccache gcc-5"
  - ccache -s
